### ISSUE TITLE
Artworks aren't properly fetched, when the soundcloud page is a set

### ISSUE THREAD

**Issue by TN1ck** [martinklepsch/soundrain#13]
The little images aren't in the class "artwork".

**Comment by TN1ck** [comment]
This is more complex than I thought, because the images aren't fetched with "curl - L" or "client/get". Don't know what would the best solution is...mmh.

**Comment by martinklepsch** [comment]
I don't quite understand the problem here.
What is the difference between an artwork and the image that is shown on the results page?

**Comment by TN1ck** [comment]
The images at the result page are the artworks, but when the url is a set (your example), the images of the songs aren't in the html source :(
