### ISSUE TITLE
When the title got a " / ", the file cannot be found.

### ISSUE THREAD

**Issue by TN1ck** [martinklepsch/soundrain#17]
Test it with: 

https://soundcloud.com/theeconomist/s

**Comment by muxamilian** [comment]
It seems to work, doesn't it?

**Comment by TN1ck** [comment]
@conchulio No it doesn't. Steps to reproduce:
1. Paste https://soundcloud.com/theeconomist/s in the search box
2. Search and download the file
3. Drop in it into the Dragzone 
4. FILE_NOT_FOUND

**Comment by muxamilian** [comment]
Fixed. Inserting "|"instead of "/"
