### ISSUE TITLE
Filesystem error: Unknown Error

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/soundrain#21]
When dragging a track into the dropzone:

```
Filesystem error: Unknown Error
```

Google Chrome Version 24.0.1312.69 on recent Ubuntu

**Comment by muxamilian** [comment]
Do you know which file you dragged? I think this helps.

**Comment by martinklepsch** [comment]
Unfortunately I don't. I'm sorry, should have included the link.
Feel free to close.

**Comment by muxamilian** [comment]
This is really mysterious. When you encounter it again, please tell me ;)
