### ISSUE TITLE
User will download the stream from soundcloud

### ISSUE THREAD

**Issue by TN1ck** [martinklepsch/soundrain#4]
Scripper will write the id3tag onto the stream, the stream itself will be downloaded from the user, no interaction of scripper.

**Comment by martinklepsch** [comment]
please elaborate :smiley: 
(sources, specific problems, whatever)

**Comment by TN1ck** [comment]
oh, wrong issue :D

**Comment by martinklepsch** [comment]
das hier is alt und invalid oder?
