### ISSUE TITLE
implement MP3 tagging via drag n drop

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/soundrain#6]
- [ ] add drag n drop area to scripper result page
- [ ] implement matcher between filename and streamurl
- [ ] prepend ID3 container and write back to disk

Maybe changing the file name would also be a nice feature.
Don't know if thats possible though.

**Comment by muxamilian** [comment]
No writing to disk yet. You can drag files anywhere. However, currently only works for one file.
